version: '3.1'
services:

# csdl
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"

      # ql csdl
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

# backend
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_HOST=db
# S3
  S3:
    image: ubuntu/apache2:2.4-20.04_beta
    ports:
      - "3131:80"
    restart: always
    volumes:
      - ./backend/img:/var/www/html
